package-lock.json
package.json
src/OKRMain.tsx
src/Objective/ObjectivePage.tsx
src/SampleDataPage.tsx
src/test.json
vss-extension.json

Adds routing and the ability to add sample data. Also fetches data from the "objectives" collection, just as a proof of concept.

Routing and sample data

---

src/DetailView/DetailOKR.scss
src/DetailView/DetailOKR.tsx
src/DetailView/DetailOKRList.tsx
src/DetailView/DetailView.scss
src/DetailView/DetailView.tsx
src/OKRMain.tsx
src/Objective/Objective.ts
src/Objective/ObjectiveService.ts
src/okr-hub.html
vss-extension.json

Add objective detail view

---

src/AddPanel/AddOKRPanel.tsx
src/DetailView/DetailOKRHeader.tsx
src/DetailView/DetailView.scss
src/DetailView/DetailView.tsx
src/DetailView/DetailViewContracts.ts
src/DetailView/DetailViewMenu.tsx
src/DetailView/DetailViewReducer.ts
src/Objective/Objective.ts
src/StateProvider.tsx
vss-extension.json

Experimental of React context plus hook

---

src/AreaView/AreaCard/AreaCard.tsx
src/AreaView/AreaCard/AreaCardDetails.tsx
src/MutableField.tsx

Added a MutableField component, which renders a label for a value, but switches to an input when clicked. An onSave function prop is called when the input loses tab, unless the user presses escape.

Added mutable fields.

---

src/Objective/ObjectiveService.ts

Just updatin' for a better demo

Update test data

---

package-lock.json
package.json
src/DetailView/DetailViewActions.ts
src/DetailView/DetailViewMenu.tsx
src/DetailView/DetailViewReducer.ts
src/OKRConstants.ts
src/OKRMain.tsx
vss-extension.json

Adding in state based nav #15 . I've removed react-router, since we don't have access to the url it was equivalent to implement the state myself :( 
I added some buttons to the top to help navigate around while we are still in development.

Add state based nav

---

package-lock.json
package.json
src/AreaView/AreaCard/ActiveCardProgress.tsx
src/AreaView/AreaGrid.tsx
src/Data/OKRDataService.ts
src/DetailView/DetailOKR.tsx
src/DetailView/DetailOKRList.tsx
src/Identity/IdentityProvider.ts
src/OKRHub.tsx
src/OKRMain.tsx
src/SampleDataPage.tsx
src/okr-hub.html
src/test.json
tsconfig.json
vss-extension.json
webpack.config.js

This shouldn't change much about how we develop, but it is a substantial change, so something might have broken. An npm install will be necessary.
I also ran npm audit to fix most of the vulnerabilities it detected.

Switched to azure-devops-extension-sdk and hooked up live identities.

---

src/Area/AreaService.ts
src/AreaView/AreaView.tsx
src/DetailView/DetailOKRHeader.tsx
src/DetailView/DetailOKRList.tsx
src/DetailView/DetailView.tsx
src/DetailView/DetailViewActions.ts
src/DetailView/DetailViewMenu.tsx
src/DetailView/DetailViewReducer.ts
src/OKRMain.tsx
src/Objective/ObjectiveService.ts

Adding in react hooks for fetching areas and objectives. This way we can reuse code between multiple components that need the area and objectives.

Add hooks for areas and objectives

---

src/AreaView/AreaView.scss
src/OKRPanel/AddOrEditOKRPanel.scss
src/OKRPanel/OKRForm.tsx
vss-extension.json

merging from previous approval with Edit UI refactor

layout tweaks

---

src/DetailView/DetailOKR.scss
src/DetailView/DetailOKR.tsx
src/DetailView/KRComment.tsx
src/StateMangement/OKRActionTypes.ts
src/StateMangement/OKRActions.ts
src/StateMangement/OKRReducers.ts
src/StateMangement/OKRState.ts
vss-extension.json

Add/Edit Comments

---

src/AreaView/AreaView.scss
vss-extension.json

tweak layout of areaView

---

src/DetailView/DetailOKR.scss
src/DetailView/DetailOKR.tsx
src/DetailView/KRComment.tsx
src/MutableStatusDropDown.tsx
vss-extension.json

UI tweaks and layout

---

src/AreaView/AreaCard/AreaCard.tsx
src/AreaView/AreaCard/AreaCardDetails.tsx
src/AreaView/AreaGrid.tsx
src/AreaView/AreaView.tsx
src/DetailView/DetailOKR.scss
src/DetailView/DetailOKR.tsx
src/StateMangement/OKRActionTypes.ts
src/StateMangement/OKRActions.ts
src/StateMangement/OKRMiddleware.ts
src/StateMangement/OKRReducers.ts
vss-extension.json

Delete area and objective

---

src/AreaView/AreaView.scss
src/AreaView/AreaZeroData.tsx
src/DetailView/DetailView.scss
src/DetailView/ObjectiveZeroData.tsx
src/MutableStatusDropDown.tsx
vss-extension.json

zero data tweaks

---

src/AreaView/AreaView.scss
src/DetailView/DetailOKR.scss
src/DetailView/DetailView.scss
src/MutableStatusDropDown.tsx
vss-extension.json

more ui tweaks

---

src/AreaView/AreaCard/AreaCard.tsx
src/AreaView/AreaGrid.tsx
src/AreaView/AreaView.tsx
src/DetailView/DetailOKRList.tsx
src/DetailView/DetailViewMenu.tsx
src/StateMangement/OKRSelector.ts

Added in an objective selector that filters a specific area's objectives from the state.

Use objective selector

---

src/ErrorMessage.tsx

#65: Update the etag error message to be more descriptive

Update etag error message

---

src/AreaView/AreaCard/Details/AreaCardDetailsEdit.tsx
src/AreaView/AreaCard/Details/AreaCardDetailsStatic.tsx
src/AreaView/AreaView.scss
vss-extension.json

Style changes for area card

---

src/Data/OKRDataService.ts
src/DetailView/DetailOKRHeader.tsx
src/DetailView/DetailView.tsx
src/OKRMain.tsx
src/Objective/ObjectiveService.ts
src/StateMangement/OKRActionTypes.ts
src/StateMangement/OKRActions.ts
src/StateMangement/OKRMiddleware.ts
src/StateMangement/OKRReducers.ts
src/StateMangement/OKRState.ts
src/StateMangement/StateProvider.tsx

Scope Objectives to a specific time frame.

Add time frame id to OKR

---

src/AreaView/AreaView.tsx
src/DetailView/DetailOKRHeader.tsx
src/StateMangement/OKRActions.ts
src/StateMangement/OKRMiddleware.ts
src/StateMangement/OKRReducers.ts

Bug fixes around Time frames

---

src/DetailView/DetailOKRHeader.tsx
src/OKRMain.tsx
src/StateMangement/OKRActionTypes.ts
src/StateMangement/OKRActions.ts
src/StateMangement/OKRMiddleware.ts
src/StateMangement/OKRReducers.ts

Final item for #78 
Add in time frame picker

Add time frame picker

---

src/AreaView/AreaCard/AreaCardProgress.tsx
src/AreaView/AreaCard/Details/AreaCardDetails.tsx
src/AreaView/AreaView.scss
src/DetailView/DetailOKR.scss
src/DetailView/DetailOKR.tsx
src/DetailView/DetailView.scss
src/DetailView/MutableScore.tsx
src/MutableIdentity.tsx
src/MutableStatusDropDown.tsx
src/OKRPanel/LinkWorkItemForm.tsx
src/okr-hub.html
vss-extension.json

mainly:
* Fix width 100% in views
* Fix strings
* make progress circle bigger and inline
* more layout

lots of ui fixes
